using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using BussinessLogicLayer;

namespace ClinienceSystemManagement.KhamBenh
{
    public partial class Allergic : DevExpress.XtraEditors.XtraForm
    {
        public int Id;
        public Allergic()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource5.Fill();
        }

        private void btnLuu_Click(object sender, EventArgs e)
        {
            try
            {
                if (string.IsNullOrEmpty(txtTen.Text))
                {
                    lbTrangThai.Text = "*Vui lòng nhập tên";
                    txtTen.Focus();
                }
                else
                {
                    if (lkeLoai.Text == "Chọn loại")
                    {
                        lbTrangThai.Text = "*Vui lòng chọn loại";
                        lkeLoai.Focus();
                    }
                    else
                    {
                        String name = Convert.ToString(txtTen.Text);
                        String note = Convert.ToString(txtGhiChu.Text);
                        string group = lkeLoai.GetColumnValue("Allergic_Type_ID").ToString();
                        int allergicTypeId = Convert.ToInt32(group);
                        BLL_Allergic.InsertAllergic(allergicTypeId, name, note, Id);
                        this.Close();
                    }
                }
            }
            catch (Exception ex)
            {
                XtraMessageBox.Show("Lỗi" + ex.Message, "Clinience", MessageBoxButtons.OK, MessageBoxIcon.Exclamation);
            }

        }

        private void btnHuy_Click(object sender, EventArgs e)
        {
            this.Close();
        }
    }
}