using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using DataAccessLayer;
using BussinessLogicLayer;

namespace ClinienceSystemManagement.KhamBenh
{
    public partial class History : DevExpress.XtraEditors.XtraForm
    {
        public int patientId;
        public Boolean openForm = true;
        public History()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource1.Fill();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource2.Fill();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource3.Fill();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource4.Fill();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource5.Fill();
        }

        public void Disable(Boolean turn)
        {
            grcBenh.Enabled = turn;
            grcBenhNhan.Enabled = turn;
            grcCLS.Enabled = turn;
            grcThuoc.Enabled = turn;
        }
        private void History_Load(object sender, EventArgs e)
        {
            if (openForm == true)
            {
                FilterNull();
                Disable(false);
                String filter = "[Precription_ID] ='" + 0 + "'";
                gvBenhNhan.ActiveFilterString = filter;
            }
            else
            {
                Disable(true);
                FillData();
                Filter();
                FilterNull();
               // lkeBenhNhan.Enabled = false;
                lkeBenhNhan.Visible = true;
                btnBenhNhan.Enabled = false;
            }

        }
        public void FillData()
        {
            if (patientId != 0)
            {
                DataClinienceDataContext db = new DataClinienceDataContext();
                var human = db.Humans.Where(i => i.Account_ID == patientId).SingleOrDefault();
                var account = db.Accounts.Where(i => i.Account_ID == patientId).SingleOrDefault();
                if (account != null)
                {
                    int count = BLL_Precription.GetCountHistory(patientId);
                    lbSoLan.Text = Convert.ToString(count);
                    lbBenhNhan.Text = account.Account_Name;
                    lbDiaChi.Text = human.Account_Address;
                    lbNgheNghiep.Text = human.Account_Job;
                    lbDiaChi.Text = human.Account_Address;
                    DateTime age = Convert.ToDateTime(human.Account_Age);
                    int ageInYrs = DateTime.Now.Year - age.Year;
                    lbTuoi.Text = ageInYrs + " tuổi";
                    string sex = human.Account_Sex;
                    if (sex == "Nam")
                    {
                        lbGioiTinh.Text = "Nam";
                    }
                    else
                    {
                        lbGioiTinh.Text = "Nu";
                    }
                    peAnh.EditValue = account.Account_Image;
                }
            }
        }
        public void FilterNull()
        {
            String filter = "[Precription_ID] ='" + 0 + "'";
            gvBenh.ActiveFilterString = filter;
            gvCLS.ActiveFilterString = filter;
            gvThuoc.ActiveFilterString = filter;
            
        }
        public void Filter()
        {
            String patient = Convert.ToString(patientId);
            String filter = "[Account_ID_Patient] ='" + patient + "'";
            gvBenhNhan.ActiveFilterString = filter;
        }
        private void btnBenhNhan_Click(object sender, EventArgs e)
        {
            if (lkeBenhNhan.Text == "Chọn bệnh nhân")
            {
                lbTrangThai.Text = "*Vui lòng chọn bệnh nhân";
                lkeBenhNhan.Focus();
            }
            else
            {
                string group = lkeBenhNhan.GetColumnValue("Account_ID").ToString();
                int patient = Convert.ToInt32(group);
                patientId = patient;
                Disable(true);
                FillData();
                Filter();
            }

        }

        private void grcBenhNhan_Click(object sender, EventArgs e)
        {
            int rowIndex = gvBenhNhan.FocusedRowHandle;
            string colID = "Precription_ID";
            object value = gvBenhNhan.GetRowCellValue(rowIndex, colID);
            if (value != null)
            {
                int preId = (int)value;
                String precription = Convert.ToString(preId);
                String filter = "[Precription_ID] ='" + precription + "'";
                gvBenh.ActiveFilterString = filter;
                gvCLS.ActiveFilterString = filter;
                gvThuoc.ActiveFilterString = filter;
            }
        }
    }
}