using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using DataAccessLayer;

namespace ClinienceSystemManagement.KhamBenh
{
    public partial class Patient : DevExpress.XtraEditors.XtraForm
    {
        public Patient()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource1.Fill();
        }
        private Form IsExits(Type type)
        {
            foreach (Form f in this.MdiChildren)
            {
                if (f.GetType() == type)
                {
                    return f;
                }
            }
            return null;
        }
        private void btnThem_Click(object sender, EventArgs e)
        {
            Form frm = this.IsExits(typeof(PatientDetail));
            if (frm != null)
            {
                frm.Activate();
            }
            else
            {
                PatientDetail pd = new PatientDetail();
                pd.isAdd = true;
                pd.ShowDialog();
                sqlDataSource1.Fill();
            }
        }

        private void btnLamMoi_Click(object sender, EventArgs e)
        {
            sqlDataSource1.Fill();
        }

        private void grcDanhMuc_Click(object sender, EventArgs e)
        {
            int rowIndex = gvDanhMuc.FocusedRowHandle;
            string colID = "Account_ID";
            object value = gvDanhMuc.GetRowCellValue(rowIndex, colID);
            if (value != null)
            {
                int Id = (int)value;
                DataClinienceDataContext db = new DataClinienceDataContext();
                var account = db.Accounts.Where(i => i.Account_ID == (int)Id).SingleOrDefault();
                var human = db.Humans.Where(i => i.Account_ID == (int)Id).SingleOrDefault();
                if (account != null)
                {
                    lbTen.Text = account.Account_Name;
                    lbDiaChi.Text = human.Account_Address;
                    lbEmail.Text = human.Account_Address;
                    lbGioiTinh.Text = human.Account_Sex;
                    lbSoDienThoai.Text = human.Account_Phone;
                    lbThanhPho.Text = human.Account_City;
                    lbTuoi.Text = Convert.ToString(human.Account_Age);
                }
                else
                {
                    XtraMessageBox.Show("Bạn chưa chọn đối tượng để xem thông tin chi tiết", "Clinience", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                }
            }
        }
    }
}