using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using BussinessLogicLayer;

namespace ClinienceSystemManagement.HeThong
{
    public partial class ChiTietCanLamSang : DevExpress.XtraEditors.XtraForm
    {
        public ChiTietCanLamSang()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource1.Fill();
        }

        private void btnHuy_Click(object sender, EventArgs e)
        {
            this.Close();
        }
        private void Reset()
        {
            txtTen.Text = "";
            txtMa.Text = "";
            txtGiaTriNho.Text = "";
            txtGiaTriLon.Text = "";
            txtTenKhac.Text = "";
            txtDonVi.Text = "";
            txtDanhMuc.Text = "";
            txtDiaChi.Text = "";
            txtGhiChu.Text = "";
            txtMoTa.Text = "";
            txtThamChieu.Text = "";
        }
        private void btnTao_Click(object sender, EventArgs e)
        {
            try
            {
                if (string.IsNullOrEmpty(txtTen.Text))
                {
                    XtraMessageBox.Show("Vui lòng nhập tên cận lâm sàng", "Clinience", MessageBoxButtons.OK, MessageBoxIcon.Exclamation);
                    txtTen.Focus();
                }
                else
                {
                    if (string.IsNullOrEmpty(txtMa.Text))
                    {   
                        XtraMessageBox.Show("Vui lòng nhập mã cận lâm sàng", "Clinience", MessageBoxButtons.OK, MessageBoxIcon.Exclamation);
                        txtMa.Focus();
                    }
                    else
                    {
                        if (lkePhanNhom.Text == "Chọn nhóm")
                        {
                            XtraMessageBox.Show("Vui lòng chọn nhóm cận lâm sàng", "Clinience", MessageBoxButtons.OK, MessageBoxIcon.Exclamation);
                            lkePhanNhom.Focus();
                        }
                        else
                        {
                            string tenCanLamSang = txtTen.Text;
                            string ma = txtMa.Text;
                            int giaTriNho = Convert.ToInt32(txtGiaTriNho.Value.ToString());
                            int giaTriLon = Convert.ToInt32(txtGiaTriLon.Value.ToString());
                            string tenKhac = txtTenKhac.Text;
                            string donVi = txtDonVi.Text;
                            string danhMuc = txtDanhMuc.Text;
                            string diaChi = txtDiaChi.Text;
                            string ghiChu = txtGhiChu.Text;
                            string moTa = txtMoTa.Text;
                            string thamChieu = txtThamChieu.Text;
                            string phanNhom = lkePhanNhom.GetColumnValue("Paraclinical_Group_ID").ToString();
                            int maNhom = Convert.ToInt32(phanNhom.ToString());
                            BLL_CanLamSang.Them(tenCanLamSang, ma, giaTriNho, giaTriLon, tenKhac, donVi, danhMuc, diaChi, ghiChu, moTa, thamChieu, maNhom);
                            this.Close();
                        }
                    }
                }
            }
            catch (Exception)
            {
                MessageBox.Show("Mã danh mục này đã tồn tại");
            }
        }

        private void ThemDanhMucCanLamSang_Load(object sender, EventArgs e)
        {

        }

    }
}