using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using ClinienceSystemManagement.HeThong;
using DataAccessLayer;

namespace ClinienceSystemManagement
{
    public partial class DanhMucCanLamSang : DevExpress.XtraEditors.XtraForm
    {
        public DanhMucCanLamSang()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource1.Fill();
        }
        private Form KiemTraTonTai(Type type)
        {
            foreach (Form f in this.MdiChildren)
            {
                if (f.GetType() == type)
                {
                    return f;
                }
            }
            return null;
        }
        private void btnThem_Click(object sender, EventArgs e)
        {
            Form frm = this.KiemTraTonTai(typeof(ChiTietCanLamSang));
            if (frm != null)
            {
                frm.Activate();
            }
            else
            {
                ChiTietCanLamSang formThemCanLamSang = new ChiTietCanLamSang();
                formThemCanLamSang.ShowDialog();     
                sqlDataSource1.Fill();
            }
        }
        public void button1_Click(object sender, EventArgs e)
        {
            sqlDataSource1.Fill();
        }
        private void btnLamMoi_Click(object sender, EventArgs e)
        {
            sqlDataSource1.Fill();
        }

        private void cmsCapNhat_Click(object sender, EventArgs e)
        {

        }

        private void cmsXoa_Click(object sender, EventArgs e)
        {
            if (XtraMessageBox.Show("Bạn có muốn xóa không?","Clinience",MessageBoxButtons.YesNo,MessageBoxIcon.Question) == DialogResult.Yes)
            {
                int rowIndex = gvData.FocusedRowHandle;
                string colID = "Paraclinical_ID";
                string colName = "Paraclinical_Name";
                object value = gvData.GetRowCellValue(rowIndex, colID);
                if (value != null)
                {
                    DataClinienceDataContext db = new DataClinienceDataContext();
                    var danhMuc = db.Paraclinicals.Where(s => s.Paraclinical_ID == value).SingleOrDefault();
                    if(danhMuc != null)
                    {
                        db.Paraclinicals.DeleteOnSubmit(danhMuc);
                        db.SubmitChanges();
                        sqlDataSource1.Fill();
                        XtraMessageBox.Show("Đã xóa thành công", "Clinience", MessageBoxButtons.OK, MessageBoxIcon.Information);     
                    }      
                }
                else
                {
                    XtraMessageBox.Show("Bạn chưa chọn đối tượng cần xóa", "Clinience", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                }

            }
        }
    }

}