using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using DataAccessLayer;

namespace ClinienceSystemManagement.HeThong
{
    public partial class Disease : DevExpress.XtraEditors.XtraForm
    {
        public Disease()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource2.Fill();
        }
        private Form IsExits(Type type)
        {
            foreach (Form f in this.MdiChildren)
            {
                if (f.GetType() == type)
                {
                    return f;
                }
            }
            return null;
        }
        private void btnThem_Click(object sender, EventArgs e)
        {
            Form frm = this.IsExits(typeof(DiseaseDetail));
            if (frm != null)
            {
                frm.Activate();
            }
            else
            {
                DiseaseDetail dd = new DiseaseDetail();
                dd.isAdd = true;
                dd.ShowDialog();
                sqlDataSource2.Fill();
            }
        }

        private void btnLamMoi_Click(object sender, EventArgs e)
        {
            sqlDataSource2.Fill();
        }

        private void cmsCapNhat_Click(object sender, EventArgs e)
        {
            int rowIndex = gvDanhMuc.FocusedRowHandle;
            string colID = "Disease_ID";
            object value = gvDanhMuc.GetRowCellValue(rowIndex, colID);
            if (value != null)
            {
                DiseaseDetail dd = new DiseaseDetail();
                dd.Id = (string)value;
                dd.isAdd = false;
                dd.ShowDialog();
                sqlDataSource2.Fill();

            }
            else
            {
                XtraMessageBox.Show("Bạn chưa chọn đối tượng để cập nhật", "Clinience", MessageBoxButtons.OK, MessageBoxIcon.Warning);
            }
        }

        private void cmsXoa_Click(object sender, EventArgs e)
        {
            try
            {
                if (XtraMessageBox.Show("Bạn có muốn xóa không?", "Clinience", MessageBoxButtons.YesNo, MessageBoxIcon.Question) == DialogResult.Yes)
                {
                    int rowIndex = gvDanhMuc.FocusedRowHandle;
                    string colID = "Disease_ID";
                    object value = gvDanhMuc.GetRowCellValue(rowIndex, colID);
                    if (value != null)
                    {
                        DataClinienceDataContext dc = new DataClinienceDataContext();
                        var para = dc.Diseases.Where(s => s.Disease_ID == (string)value).SingleOrDefault();
                        if (para != null)
                        {
                            dc.Diseases.DeleteOnSubmit(para);
                            dc.SubmitChanges();
                            sqlDataSource2.Fill();
                            XtraMessageBox.Show("Đã xóa thành công", "Clinience", MessageBoxButtons.OK, MessageBoxIcon.Information);
                        }
                    }
                    else
                    {
                        XtraMessageBox.Show("Bạn chưa chọn đối tượng cần xóa", "Clinience", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                    }
                }
            }
            catch (Exception)
            {

                XtraMessageBox.Show("Không được phép xóa đối tượng này, đối tượng đã được thêm ở một danh mục khác", "Clinience", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
          
        }
    }
}