using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using DataAccessLayer;
using BussinessLogicLayer;

namespace ClinienceSystemManagement.HeThong
{
    public partial class HumanDetail : DevExpress.XtraEditors.XtraForm
    {
        public int Id;
        public bool isAdd = true;
        private string tenDangNhap;

        public HumanDetail()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource2.Fill();
        }



        // Event show dialog to choice path when click insert a image 
        public void peAnh_Click(object sender, EventArgs e)
        {
            try
            {
                OpenFileDialog openFileDialog = new OpenFileDialog();
                openFileDialog.Filter = ("Image Files |*.png; *.bmp; *.jpg;*.jpeg; *.gif;");
                openFileDialog.FilterIndex = 4;
                openFileDialog.RestoreDirectory = true;
                if (openFileDialog.ShowDialog() == DialogResult.OK)
                {
                    txtAnh.Text = openFileDialog.FileName;
                    peAnh.Image = Image.FromFile(openFileDialog.FileName);
                }
            }
            catch (Exception ex)
            {
                XtraMessageBox.Show("Không thể tải được ảnh", ex.Message);
            }

        }

        private void HumanDetail_Load(object sender, EventArgs e)
        {
            FillDataUpdate();
            txtMa.ReadOnly = true;
        }

        public void FillDataUpdate()
        {
            if (Id != 0)
            {
                DataClinienceDataContext db = new DataClinienceDataContext();
                var account = db.Accounts.Where(i => i.Account_ID == (int)Id).SingleOrDefault();
                if (account != null)
                {
                    txtTen.EditValue = account.Account_Name;
                    txtMa.EditValue = account.Account_ID;
                    txtTenDangNhap.EditValue = account.Account_UserName;
                    peAnh.EditValue = account.Account_Image;
                    txtKiTe.EditValue = account.Account_Signatures;
                    txtMatKhau.EditValue = account.Account_Password;
                    lkePhanQuyen.EditValue = account.Account_Type_ID;
                    txtMatKhau2.EditValue = account.Account_Password;
                    txtMa.ReadOnly = true;
                }
            }
        }

        private void SaveUpdate()
        {
            try
            {
                if (string.IsNullOrEmpty(txtTen.Text))
                {
                    XtraMessageBox.Show("Vui lòng nhập tên người sử dụng", "Clinience", MessageBoxButtons.OK, MessageBoxIcon.Exclamation);
                    txtTen.Focus();
                }
                else
                {
                    if (string.IsNullOrEmpty(txtTenDangNhap.Text))
                    {
                        XtraMessageBox.Show("Vui lòng nhập tên đăng nhập", "Clinience", MessageBoxButtons.OK, MessageBoxIcon.Exclamation);
                        txtTenDangNhap.Focus();
                    }
                    else
                    {
                        if (lkePhanQuyen.Text == "Chọn quyền hạn")
                        {
                            XtraMessageBox.Show("Vui lòng chọn phân quyền", "Clinience", MessageBoxButtons.OK, MessageBoxIcon.Exclamation);
                            lkePhanQuyen.Focus();
                        }
                        else
                        {
                            if (txtMatKhau.Text != txtMatKhau2.Text)
                            {
                                XtraMessageBox.Show("Mật khẩu không trùng khớp", "Clinience", MessageBoxButtons.OK, MessageBoxIcon.Exclamation);
                                txtMatKhau2.Focus();
                            }
                            else
                            {
                                int id = Int32.Parse(txtMa.Text);
                                string name = txtTen.Text;
                                string username = txtTenDangNhap.Text;
                                string password = txtMatKhau.Text;
                                string image = txtAnh.Text;
                                string signature = txtKiTe.Text;
                                string group = lkePhanQuyen.GetColumnValue("Account_Type_ID").ToString();
                                int type = Int32.Parse(group);
                                if (string.IsNullOrEmpty(txtAnh.Text))
                                {
                                    BLL_Human.UpdateAccountNoImage(id, name, username, password, signature, type);
                                    this.Close();
                                    XtraMessageBox.Show("Cập nhật thành công", "Clinience", MessageBoxButtons.OK, MessageBoxIcon.Information);
                                }
                                else
                                {
                                    BLL_Human.UpdateAccount(id, name, username, password, image, signature, type);
                                    this.Close();
                                    XtraMessageBox.Show("Cập nhật thành công", "Clinience", MessageBoxButtons.OK, MessageBoxIcon.Information);
                                }
                            }
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show("Lỗi" + ex.Message);
            }
        }
        private void btnTao_Click(object sender, EventArgs e)
        {
            try
            {
                if (isAdd == false)
                {
                    SaveUpdate();
                }
                else
                {
                    if (string.IsNullOrEmpty(txtTen.Text))
                    {
                        XtraMessageBox.Show("Vui lòng nhập tên người sử dụng", "Clinience", MessageBoxButtons.OK, MessageBoxIcon.Exclamation);
                        txtTen.Focus();
                    }
                    else
                    {
                        if (string.IsNullOrEmpty(txtTenDangNhap.Text))
                        {
                            XtraMessageBox.Show("Vui lòng nhập tên đăng nhập", "Clinience", MessageBoxButtons.OK, MessageBoxIcon.Exclamation);
                            txtTenDangNhap.Focus();
                        }
                        else
                        {
                            if (lkePhanQuyen.Text == "Chọn quyền hạn")
                            {
                                XtraMessageBox.Show("Vui lòng chọn phân quyền", "Clinience", MessageBoxButtons.OK, MessageBoxIcon.Exclamation);
                                lkePhanQuyen.Focus();
                            }
                            else
                            {
                                if (string.IsNullOrEmpty(txtMatKhau.Text))
                                {
                                    XtraMessageBox.Show("Vui lòng nhập mật khẩu", "Clinience", MessageBoxButtons.OK, MessageBoxIcon.Exclamation);
                                    txtMatKhau.Focus();
                                }
                                else
                                {
                                    if (txtMatKhau.Text != txtMatKhau2.Text)
                                    {
                                        XtraMessageBox.Show("Mật khẩu không trùng khớp", "Clinience", MessageBoxButtons.OK, MessageBoxIcon.Exclamation);
                                        txtMatKhau2.Focus();
                                    }
                                    else
                                    {

                                        string name = txtTen.Text;
                                        string username = txtTenDangNhap.Text;
                                        string password = txtMatKhau.Text;
                                        string image = txtAnh.Text;
                                        string signature = txtKiTe.Text;
                                        string group = lkePhanQuyen.GetColumnValue("Account_Type_ID").ToString();
                                        int type = Int32.Parse(group);
                                        int count = BLL_Human.Select_Username(username).Rows.Count;
                                        if (count > 0)
                                        {
                                            XtraMessageBox.Show("Tên đăng nhập đã tồn tại", "Clinience", MessageBoxButtons.OK, MessageBoxIcon.Exclamation);
                                            txtTenDangNhap.Focus();
                                        }
                                        else
                                        {
                                            if (string.IsNullOrEmpty(txtAnh.Text))
                                            {
                                                BLL_Human.InsertAccountNoImage(name, username, password, signature, type);
                                                this.Close();
                                            }
                                            else
                                            {
                                                BLL_Human.InsertAccount(name, username, password, image, signature, type);
                                                this.Close();
                                            }
                                        }

                                    }
                                }
                            }
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show("Lỗi :" + ex.Message);
            }
        }

        private void cbxHienMatKhau_CheckedChanged(object sender, EventArgs e)
        {
            if (cbxHienMatKhau.Checked)
            {
                this.txtMatKhau.Properties.UseSystemPasswordChar = false;
                this.txtMatKhau2.Properties.UseSystemPasswordChar = false;
            }
            else
            {
                this.txtMatKhau.Properties.UseSystemPasswordChar = true;
                this.txtMatKhau2.Properties.UseSystemPasswordChar = true;
            }
        }

        private void btnHuy_Click(object sender, EventArgs e)
        {
            this.Close();
        }

        private void txtMatKhau_Validating(object sender, CancelEventArgs e)
        {
            if (txtMatKhau.Text.Length > 10 || txtMatKhau.Text.Length < 4)
            {
                XtraMessageBox.Show("Mật khẩu phải từ 4 đến 10 kí tự", "Clinience", MessageBoxButtons.OK, MessageBoxIcon.Exclamation);
                txtMatKhau.Focus();
            }
        }

        private void txtTenDangNhap_Validating(object sender, CancelEventArgs e)
        {
            if (txtTenDangNhap.Text.Length > 20 || txtTenDangNhap.Text.Length < 5)
            {
                XtraMessageBox.Show("Tên đăng nhập phải từ 5 đến 20 kí tự", "Clinience", MessageBoxButtons.OK, MessageBoxIcon.Exclamation);
                txtTenDangNhap.Focus();
            }
        }
    }
}