using System;
using System.Collections.Generic;
using System.Linq;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using ClinienceSystemManagement.HeThong;
using DataAccessLayer;

namespace ClinienceSystemManagement
{
    public partial class DanhMucCanLamSang : DevExpress.XtraEditors.XtraForm
    {
        public DanhMucCanLamSang()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource1.Fill();
        }

        private Form IsExits(Type type)
        {
            foreach (Form f in this.MdiChildren)
            {
                if (f.GetType() == type)
                {
                    return f;
                }
            }
            return null;
        }

        private void btnThem_Click(object sender, EventArgs e)
        {
            Form frm = this.IsExits(typeof(ParaclinicalDetail));
            if (frm != null)
            {
                frm.Activate();
            }
            else
            {
                ParaclinicalDetail pd = new ParaclinicalDetail();
                pd.isAdd = true;
                pd.ShowDialog();
                sqlDataSource1.Fill();
            }
        }

        private void btnLamMoi_Click(object sender, EventArgs e)
        {
            sqlDataSource1.Fill();
        }

        private void cmsCapNhat_Click(object sender, EventArgs e)
        {
            int rowIndex = gvData.FocusedRowHandle;
            string colID = "Paraclinical_ID";
            object value = gvData.GetRowCellValue(rowIndex, colID);
            if (value != null)
            {
                ParaclinicalDetail pd = new ParaclinicalDetail();
                pd.Id = (string)value;
                pd.isAdd = false;
                pd.ShowDialog();
                sqlDataSource1.Fill();
             
            }
            else
            {
                XtraMessageBox.Show("Bạn chưa chọn đối tượng để cập nhật", "Clinience", MessageBoxButtons.OK, MessageBoxIcon.Warning);
            }
        }
        private void cmsXoa_Click(object sender, EventArgs e)
        {
            if (XtraMessageBox.Show("Bạn có muốn xóa không?", "Clinience", MessageBoxButtons.YesNo, MessageBoxIcon.Question) == DialogResult.Yes)
            {
                int rowIndex = gvData.FocusedRowHandle;
                string colID = "Paraclinical_ID";
                object value = gvData.GetRowCellValue(rowIndex, colID);
                if (value != null)
                {
                    DataClinienceDataContext dc = new DataClinienceDataContext();
                    var para = dc.Paraclinicals.Where(s => s.Paraclinical_ID == (string)value).SingleOrDefault();
                    if (para != null)
                    {
                        dc.Paraclinicals.DeleteOnSubmit(para);
                        dc.SubmitChanges();
                        sqlDataSource1.Fill();
                        XtraMessageBox.Show("Đã xóa thành công", "Clinience", MessageBoxButtons.OK, MessageBoxIcon.Information);
                    }
                }
                else
                {
                    XtraMessageBox.Show("Bạn chưa chọn đối tượng cần xóa", "Clinience", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                }
            }
        }

        private void btnTimKiem_Click(object sender, EventArgs e)
        {
            string data = txtTimKiem.Text;
            txtTimKiem.Text = "";
        }
       
    }
}