using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using BussinessLogicLayer;

namespace ClinienceSystemManagement.HeThong
{
    public partial class Statictis : DevExpress.XtraEditors.XtraForm
    {
        public Statictis()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource1.Fill();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource2.Fill();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource3.Fill();
        }

        private void btnHuy_Click(object sender, EventArgs e)
        {
            this.Close();
        }
        private void HandleVisible(Boolean turn)
        {
            lbBatDau.Enabled = turn;
            lbKetThuc.Enabled = turn;
            dtBatDau.Enabled = turn;
            dtKetThuc.Enabled = turn;
        }


        private void Statictis_Load(object sender, EventArgs e)
        {
          
        }

        private void btnThongKe_Click(object sender, EventArgs e)
        {
            if (lkeThoiDiem.Text == "Chọn thời điểm")
            {
                lbTrangThai.Text = "*Vui lòng chọn thời điểm";
                lkeThoiDiem.Focus();
            }
            else
            {
                DateTime date = DateTime.Now;
                string group = lkeThoiDiem.GetColumnValue("Id").ToString();
                int groupId = Convert.ToInt32(group);
           
                int Amount = 0;
                //Today
                if (groupId == 1)
                {
                    Amount = BLL_Clinience.GetAmountByDay(date);
                    lbTien.Text = Convert.ToString(Amount);
                }
                else
                {
                    if (groupId == 2)
                    {
                        Amount = BLL_Clinience.GetAmountByMonth(date);
                        lbTien.Text = Convert.ToString(Amount);
                    }
                    else
                    {
                        if (groupId == 3)
                        {
                            Amount = BLL_Clinience.GetAmountByYear(date);
                            lbTien.Text = Convert.ToString(Amount);
                        }
                        else
                        {
                            if (groupId == 6)
                            {
                                Amount = BLL_Clinience.GetAmountByALL();
                                lbTien.Text = Convert.ToString(Amount);
                            }
                            else
                            {
                                DateTime beginDate = dtBatDau.DateTime;
                                DateTime endDate = dtKetThuc.DateTime;
                                Amount = BLL_Clinience.GetAmountByOption(beginDate, endDate);
                                lbTien.Text = Convert.ToString(Amount);
                            }
                        }
                    }
                }

            }
        }

        
    }
}