using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using BussinessLogicLayer;
using DevExpress.XtraGrid.Views.Grid;
using DevExpress.XtraGrid.Columns;

namespace ClinienceSystemManagement.HeThong
{
    public partial class Statictis : DevExpress.XtraEditors.XtraForm
    {
        public Statictis()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource1.Fill();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource2.Fill();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource3.Fill();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource4.Fill();
        }

        private void btnHuy_Click(object sender, EventArgs e)
        {
            this.Close();
          
        }

        private void HandleVisible(Boolean turn)
        {
            lbBatDau.Visible = turn;
            lbKetThuc.Visible = turn;
            dtBatDau.Visible = turn;
            dtKetThuc.Visible = turn;
            label2.Visible = turn;
        }


        private void Statictis_Load(object sender, EventArgs e)
        {
            HandleVisible(false);
            String filter = "[Precription_Date] ='01/01/1000'";
            gvDanhMuc.ActiveFilterString = filter;
        }

        private void btnThongKe_Click(object sender, EventArgs e)
        {
            if (lkeThoiDiem.Text == "Chọn thời điểm")
            {
                lbTrangThai.Text = "*Vui lòng chọn thời điểm";
                lkeThoiDiem.Focus();
            }
            else
            {
                DateTime date = DateTime.Now;
                var day = date.Date;
                var month = date.Month;
                var year = date.Year;
                string group = lkeThoiDiem.GetColumnValue("Id").ToString();
                int groupId = Convert.ToInt32(group);
                String Amount;
                //Today
                if (groupId == 1)
                {
                    String filter = "[Precription_Date] ='" + day + "'";

                    gvDanhMuc.ActiveFilterString = filter;
                    Amount = BLL_Clinience.GetAmountByDay(date);
                    if (Amount == "")
                    {
                        lbTien.Text = "0";
                    }
                    else
                    {
                        HandleVisible(false);
                        lbTien.Text = Convert.ToString(Amount);
                        lbTrangThai.Text = "";
                    }
                }
                else
                {
                    //Month
                    if (groupId == 2)
                    {
                        String filter = "[colMonth] ='" + month + "' And [colYear] ='" + year + "'";
                        gvDanhMuc.ActiveFilterString = filter;
                        Amount = BLL_Clinience.GetAmountByMonth(date);
                        if (Amount == "")
                        {
                            lbTien.Text = "0";
                        }
                        else
                        {
                            HandleVisible(false);
                            lbTien.Text = Convert.ToString(Amount);
                            lbTrangThai.Text = "";
                        }
                    }
                    else
                    {
                        //Year
                        if (groupId == 3)
                        {
                            String filter = "[colYear] ='" + year + "'";
                            gvDanhMuc.ActiveFilterString = filter;
                            Amount = BLL_Clinience.GetAmountByYear(date);
                            if (Amount == "")
                            {
                                lbTien.Text = "0";
                            }
                            else
                            {
                                HandleVisible(false);
                                lbTien.Text = Convert.ToString(Amount);
                                lbTrangThai.Text = "";
                            }
                        }
                        else
                        {
                            //ALL
                            if (groupId == 6)
                            {
                                Amount = BLL_Clinience.GetAmountByALL();
                                if (Amount == "")
                                {
                                    lbTien.Text = "0";
                                }
                                else
                                {
                                    HandleVisible(false);
                                    String filter = "";
                                    gvDanhMuc.ActiveFilterString = filter;
                                    lbTien.Text = Convert.ToString(Amount);
                                    lbTrangThai.Text = "";
                                }
                            }
                            else
                            {
                                if (string.IsNullOrEmpty(dtBatDau.Text) || string.IsNullOrEmpty(dtKetThuc.Text))
                                {
                                    lbTrangThai.Text = "*Vui lòng chọn mốc thời gian";
                                    dtBatDau.Focus();
                                    dtKetThuc.Focus();
                                    HandleVisible(true);
                                }
                                else
                                {
                                  
                                    DateTime beginDate = dtBatDau.DateTime;
                                    DateTime endDate = dtKetThuc.DateTime;
                                    if (beginDate > endDate)
                                    {
                                        lbTrangThai.Text = "*Vui lòng chọn lại thời gian đến";
                                        dtKetThuc.Focus();
                                    }
                                    else
                                    {
                                        var beginDay = beginDate.Day;
                                        var beginMonth= beginDate.Month;
                                        var beginYear = beginDate.Year;
                                        var endDay = endDate.Day;
                                        var endMonth = endDate.Month;
                                        var endYear = endDate.Year;
                                        String filter = "[colDay] >='" + beginDay + "' And [colDay] <='" + endDay + "' And [colMonth] >='" + beginMonth + "' And [colMonth] <='" + endMonth + "' And [colYear] ='" + beginYear + "'";
                                        gvDanhMuc.ActiveFilterString = filter;                               
                                        Amount = BLL_Clinience.GetAmountByOption(beginDate, endDate);
                                        if (Amount == "")
                                        {
                                            lbTien.Text = "0";
                                        }
                                        else
                                        {
                                            lbTien.Text = Convert.ToString(Amount);
                                            lbTrangThai.Text = "";
                                        }
                                    }
                                }
                            }
                        }
                    }
                }

            }
        }
    }
}